--------------------------------------------------------
--  File created - Wednesday-July-19-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USUARIO" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CLIENTE" FLOAT(126), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"FECHAALTA" DATE DEFAULT SYSDATE, 
	"FECHABAJA" DATE, 
	"STATUS" CHAR(1 BYTE) DEFAULT 'A', 
	"INTENTOS" FLOAT(126) DEFAULT 0, 
	"FECHAREVOCADO" DATE, 
	"FECHA_VIGENCIA" DATE, 
	"NO_ACCESO" NUMBER(*,0), 
	"APELLIDO_PATERNO" VARCHAR2(50 BYTE), 
	"APELLIDO_MATERNO" VARCHAR2(50 BYTE), 
	"AREA" NUMBER(4,0), 
	"FECHAMODIFICACION" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.USUARIO
SET DEFINE OFF;
Insert into SYSTEM.USUARIO (LOGIN,PASSWORD,NOMBRE,CLIENTE,EMAIL,FECHAALTA,FECHABAJA,STATUS,INTENTOS,FECHAREVOCADO,FECHA_VIGENCIA,NO_ACCESO,APELLIDO_PATERNO,APELLIDO_MATERNO,AREA,FECHAMODIFICACION) values ('AlanRom','UC1oxqCUgw1J+AdxV4KAROhJUMOSJ+MlR7khIGDjJ1E=','Luis Alan Roman x',123,'alan_rom@example.com',to_date('19-JUL-23','DD-MON-RR'),to_date('19-JUL-23','DD-MON-RR'),'A',0,null,to_date('19-JUL-23','DD-MON-RR'),0,'Roman','Becerra',3,to_date('19-JUL-23','DD-MON-RR'));
Insert into SYSTEM.USUARIO (LOGIN,PASSWORD,NOMBRE,CLIENTE,EMAIL,FECHAALTA,FECHABAJA,STATUS,INTENTOS,FECHAREVOCADO,FECHA_VIGENCIA,NO_ACCESO,APELLIDO_PATERNO,APELLIDO_MATERNO,AREA,FECHAMODIFICACION) values ('Luisfer','UC1oxqCUgw1J+AdxV4KAROhJUMOSJ+MlR7khIGDjJ1E=','Luis Fernando',123,'luis.fer@example.com',to_date('19-JUL-23','DD-MON-RR'),null,'A',0,null,to_date('20-JUL-23','DD-MON-RR'),1,'Lopez','Lara',3,to_date('19-JUL-23','DD-MON-RR'));
Insert into SYSTEM.USUARIO (LOGIN,PASSWORD,NOMBRE,CLIENTE,EMAIL,FECHAALTA,FECHABAJA,STATUS,INTENTOS,FECHAREVOCADO,FECHA_VIGENCIA,NO_ACCESO,APELLIDO_PATERNO,APELLIDO_MATERNO,AREA,FECHAMODIFICACION) values ('JorgeLo','pmWkWSBCL51Bfkhn79xPuKBKHz//H6B+mY6G9/eieuM=','Jorge',543221,'jorge.lo.rom@example.com',to_date('19-JUL-23','DD-MON-RR'),to_date('19-JUL-23','DD-MON-RR'),'A',0,null,to_date('20-JUL-23','DD-MON-RR'),30,'Lopez','Lopez',3,null);
Insert into SYSTEM.USUARIO (LOGIN,PASSWORD,NOMBRE,CLIENTE,EMAIL,FECHAALTA,FECHABAJA,STATUS,INTENTOS,FECHAREVOCADO,FECHA_VIGENCIA,NO_ACCESO,APELLIDO_PATERNO,APELLIDO_MATERNO,AREA,FECHAMODIFICACION) values ('Gabriel','pmWkWSBCL51Bfkhn79xPuKBKHz//H6B+mY6G9/eieuM=','Gabriel',543221,'1@example.com',to_date('19-JUL-23','DD-MON-RR'),to_date('19-JUL-23','DD-MON-RR'),'A',0,null,to_date('20-JUL-23','DD-MON-RR'),2,'Lopez','Aviñes',3,to_date('19-JUL-23','DD-MON-RR'));
Insert into SYSTEM.USUARIO (LOGIN,PASSWORD,NOMBRE,CLIENTE,EMAIL,FECHAALTA,FECHABAJA,STATUS,INTENTOS,FECHAREVOCADO,FECHA_VIGENCIA,NO_ACCESO,APELLIDO_PATERNO,APELLIDO_MATERNO,AREA,FECHAMODIFICACION) values ('NesDes','123','Nestor x',543221,'nes.tor@example.com',to_date('19-JUL-23','DD-MON-RR'),null,'A',0,null,to_date('18-JUL-23','DD-MON-RR'),1,'De la Torre','Martinez',3,to_date('19-JUL-23','DD-MON-RR'));
Insert into SYSTEM.USUARIO (LOGIN,PASSWORD,NOMBRE,CLIENTE,EMAIL,FECHAALTA,FECHABAJA,STATUS,INTENTOS,FECHAREVOCADO,FECHA_VIGENCIA,NO_ACCESO,APELLIDO_PATERNO,APELLIDO_MATERNO,AREA,FECHAMODIFICACION) values ('DanielMon','0KcxvlHop58FtIAFf+57N/vtXvv/EvethNapdLcvaE0=','Daniel',543221,'daniel@example.com',to_date('19-JUL-23','DD-MON-RR'),to_date('19-JUL-23','DD-MON-RR'),'A',0,null,to_date('20-JUL-23','DD-MON-RR'),20,'Monroy','Rodriguez',3,to_date('19-JUL-23','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_USUARIO" ON "SYSTEM"."USUARIO" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USUARIO" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
